# Generated by Django 5.1.1 on 2026-09-04 11:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centres', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('checked_in', 'Checked In'), ('in_queue', 'In Queue'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], db_index=True, default='booked', max_length=20)),
                ('quantity_kg', models.DecimalField(decimal_places=2, default=1000.0, help_text='Estimated crop quantity to be delivered in kilograms', max_digits=10)),
                ('qr_code_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique QR verification token presented at mandi intake gate', unique=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Direct Bank Transfer (DBT) payment amount in INR', max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('transaction_reference', models.CharField(blank=True, default='', help_text='Bank UTR / PFMS / DBT transaction reference number', max_length=100)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Payment Status',
                'verbose_name_plural': 'Payment Statuses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('capacity', models.PositiveIntegerField(default=15, help_text='Maximum number of bookings allowed in this slot window')),
                ('booked_count', models.PositiveIntegerField(default=0, help_text='Current number of active bookings registered for this slot')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='centres.procurementcentre')),
            ],
            options={
                'verbose_name': 'Slot',
                'verbose_name_plural': 'Slots',
                'ordering': ['date', 'start_time'],
                'unique_together': {('centre', 'date', 'start_time', 'end_time')},
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings.slot'),
        ),
    ]
