# Generated by Django 5.1.1 on 2026-09-04 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementCentre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Karnal Central Grain Procurement Centre', max_length=200)),
                ('address', models.TextField(help_text='Full physical address or landmark')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('district', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(default='Haryana', max_length=100)),
                ('daily_capacity', models.PositiveIntegerField(default=80, help_text='Maximum number of booking tokens/deliveries handled per operating day')),
                ('avg_processing_time_minutes', models.PositiveIntegerField(default=25, help_text='Average processing, weighing, and QC time in minutes per farmer trolley')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Procurement Centre',
                'verbose_name_plural': 'Procurement Centres',
                'ordering': ['district', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OperatingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('opening_time', models.TimeField(default='08:00:00')),
                ('closing_time', models.TimeField(default='16:00:00')),
                ('is_closed', models.BooleanField(default=False, help_text='True if centre is closed on this day (e.g. Sundays)')),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operating_hours', to='centres.procurementcentre')),
            ],
            options={
                'verbose_name': 'Operating Hours',
                'verbose_name_plural': 'Operating Hours',
                'ordering': ['centre', 'day_of_week'],
                'unique_together': {('centre', 'day_of_week')},
            },
        ),
    ]
