# Generated by Django 5.1.1 on 2026-09-04 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('centres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('token_number', models.PositiveIntegerField(help_text='Sequential token number for the centre on this operating date')),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('called', 'Called to Gate/Weighbridge'), ('processing', 'Unloading & Quality Check'), ('completed', 'Completed'), ('skipped', 'Skipped / Delayed')], db_index=True, default='waiting', max_length=20)),
                ('estimated_wait_minutes', models.PositiveIntegerField(default=0, help_text='Dynamically calculated estimated wait time in minutes')),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('served_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue_token', to='bookings.booking')),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_tokens', to='centres.procurementcentre')),
            ],
            options={
                'verbose_name': 'Queue Token',
                'verbose_name_plural': 'Queue Tokens',
                'ordering': ['date', 'token_number'],
                'unique_together': {('centre', 'date', 'token_number')},
            },
        ),
    ]
